server.port: 8080

kayttooikeus.tasks.export.enabled: true
kayttooikeus.tasks.export.bucket-name: ${export_bucket_name}
kayttooikeus.tasks.export.use-crt-client: true
kayttooikeus.tasks.export.copy-to-lampi: false
kayttooikeus.tasks.export.lampi-bucket-name: none
kayttooikeus.tasks.export.lampi-role-arn: none
kayttooikeus.tasks.export.lampi-external-id: none

spring.messages.use-code-as-default-message: true
spring.datasource.url: jdbc:postgresql://${postgres_host}:${postgres_port}/${postgres_database}?ApplicationName=kayttooikeus-service
spring.datasource.username: ${postgres_username}
spring.datasource.password: ${postgres_password}
spring.datasource.hikari.maximum-pool-size: 20
spring.datasource.hikari.connection-timeout: 10000
spring.datasource.hikari.max-lifetime: 900000

cas.service: https://virkailija.hahtuvaopintopolku.fi/kayttooikeus-service
cas.mfa.username: ${ssm_cas_mfa_username}
cas.mfa.password: ${ssm_cas_mfa_password}
cas.mfa.encryption-key: ${ssm_cas_gauth_encryption_key}
cas.mfa.signing-key: ${ssm_cas_gauth_signing_key}

host.host-virkailija: "virkailija.hahtuvaopintopolku.fi"
host.host-oppija: "hahtuvaopintopolku.fi"
host.host-cas: "virkailija.hahtuvaopintopolku.fi"
host.host-shibboleth: "tunnistus.hahtuvaopintopolku.fi"
host.host-varda: "frontend-qa.varda-db.csc.fi"

palvelukayttaja.username: ${ssm_kayttooikeus_username}
palvelukayttaja.password: ${ssm_kayttooikeus_password}

common.admin-oid: "1.2.246.562.24.00000000001"
common.crypto-password: ${ssm_kayttooikeus_crypto_password}

kayttooikeus.uses-ssl-proxy: true
kayttooikeus.disable-same-site-cookie: true
kayttooikeus.scheduling.enabled: true
kayttooikeus.kutsu.allowlist-oids: ${ssm_kayttooikeus_kutsu_allowlist}

auth.crypto-service.static-salt: ${ssm_auth_cryptoservice_static_salt}