server.port: 8101

kayttooikeus.oauth2.publickey: classpath:public_key.pem
kayttooikeus.oauth2.privatekey: classpath:private_key.pem

host-cas: localhost:8083
cas.url: http://${host-cas}/cas-oppija
cas.login: http://${host-cas}/cas-oppija/login