spring.datasource.url: jdbc:postgresql://localhost:5081/casoppija

management.endpoints.web.exposure.include: health,springWebflow,auditevents,beans
management.endpoint.auditevents.access: READ_ONLY
management.endpoint.springWebflow.access: READ_ONLY
management.endpoint.beans.access: READ_ONLY

cas.server.name: http://localhost:8081
cas.server.prefix: ${cas.server.name}/cas-oppija
cas.ticket.registry.jpa.url: ${spring.datasource.url}
cas.tgc.secure: false
cas.tgc.pin-to-session: false
cas.warning-cookie.secure: false

# Disable CAS CORS validation for testing
cas.http-web-request.cors.enabled: false

cas.authn.pac4j.saml[0].client-name: cas-oppija-keycloak
cas.authn.pac4j.saml[0].auto-redirect-type: CLIENT
cas.authn.pac4j.saml[0].keystore-password: dummy
cas.authn.pac4j.saml[0].private-key-password: dummy
cas.authn.pac4j.saml[0].keystore-path: keycloak/localkeystore.jks
# Remember to use the Client Id defined for the corresponding keycloak client as the service-provider-entity-id
cas.authn.pac4j.saml[0].service-provider-entity-id: http://localhost:8081/cas-oppija
cas.authn.pac4j.saml[0].service-provider-metadata-path: keycloak/sp-metadata.xml
cas.authn.pac4j.saml[0].identity-provider-metadata-path: keycloak/idp-metadata.xml
cas.authn.pac4j.saml[0].principal-attribute-id: nationalIdentificationNumber
cas.authn.pac4j.saml[0].requested-attributes[0].name: urn:oid:1.2.246.21
cas.authn.pac4j.saml[0].requested-attributes[0].friendly-name: nationalIdentificationNumber
cas.authn.pac4j.saml[0].requested-attributes[0].name-format: urn:oasis:names:tc:SAML:2.0:attrname-format:uri
cas.authn.pac4j.saml[0].requested-attributes[0].required: true
cas.authn.pac4j.saml[0].requested-attributes[1].name: urn:oid:2.5.4.3
cas.authn.pac4j.saml[0].requested-attributes[1].friendly-name: cn
cas.authn.pac4j.saml[0].requested-attributes[1].name-format: urn:oasis:names:tc:SAML:2.0:attrname-format:uri
cas.authn.pac4j.saml[0].requested-attributes[1].required: true
cas.authn.pac4j.saml[0].mapped-attributes[0]: personName->urn:oid:2.5.4.3

cas.monitor.endpoints.endpoint.springWebflow.access: PERMIT
cas.logout.follow-service-redirects: true
cas.logout.redirect-parameter: service
cas.logout.redirect-url: https://localhost:8080/

host.alb: localhost:8101

kayttooikeus.baseurl: http://host.docker.internal:8101/kayttooikeus-service
oppijanumerorekisteri.baseurl: http://localhost:8084
oauth2.client-id: cas-oppija
oauth2.client-secret: cas-oppija-oauth2-secret
user-controller.enabled: true
