services:
  cas:
    container_name: cas-virkailija
    image: cas-virkailija:latest
    ports:
     - "8443:8443"
     - "8080:8080"
    environment:
      ENV: local
      haka_keystore_base64: ""
      haka_sp_metadata: ""