sudo: required
dist: bionic
language: java
jdk:
  - openjdk11
services:
  - docker
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2
env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "azDaqzCziZ2z2phMWdBpeiXnPzhriXuZG64/VZ+tUJ2B6TR6feHbKj1CPgSU7SBE0AEx3X3Z+UVtmg7cYNMxASvANzSooA4blXdGuOghD2jZsrqyF2x45rbb80LkU107aWO1SvoGGRNtzTDRJ5pNeyq+OcPfWVH6RSmH/6mJ40pBx3Zc0bvtAixKLUmVXtxrv37MNSWDzae7TN4GhObEIoGaOgVaQHxj8hxFAgHzwet2LbO1q4GkeKMq9VjEllTOdzHBnoCmtCYiA6RSr5LO8C+yTDRP9teGmUqrj2b+Qb0rcP+KYjn32Z6lCBo0RiOv0eiBH/LTRN2G247GE9VTStMqtTg9p5vyEFovKoOyBCF3Hjsj3b03fGy+7Cy3FPSFeeBJEstAOkdXbESanw4Fft5gYOJPimh/jeGxj96r0lwbaX7XHCZvlB3Pwx5pUMUxGzOqCXN/gfd/NadoBkICf2gxk7FfbFcwHqVQmPmN1pTLZpGEMOw+593mSfKIVhHKDVPALW7rQaf7CbyqLoZ6snjAeBHHd3p/ksdRqKfVOUCz1xka1Y9Q0UCEK9jnOGS1a03Q2EDAukGzQkg7BotVrsysnwASDObDMDUYEkMWNuLKuaV08aJojA4lPZcuhKhrWMoFkARW7sVEkoBTBL3L+8Bg8F8vAKB0pTOK4fGv220="
    # AWS_SECRET_ACCESS_KEY
    - secure: "pwt3CVXGXMSPg94q+7bNBy2WPS9jVjB/d/5VGAdgEnOBFc4ibgcaXzhI8J1eBMibKZz0avPjQ04ToSuFGcHI4PTlhjFx2Lbm+/Kgtme4JekaKS7sBTwnCxgm25MbfnSVnCiUQPdMDAb83dLAe4TqtKqE7QLLjDzvRT8Z67V1+64tfgJwMESfxlNkkRv6T4SolBnEX7JOLlRBPp7BsSK0FJbFJ42hBdlxe6mWd7RVZO9lS6yhN86WusVhHH0uTPZCCQZkZkP8bDFhDh1hlkMFnPXHTrTRkhigXy33EjW6J3KOUoz4bzPlmxsAjjxsV0U8dp+n5sa/5valDgM9/KxWEgY3UDtrJqwfrx4gv5cUCPEioYoGuLfpqdGc0iQDzGlrGRicU6VjTO7zO0egdEVw6zM4v179WLylT3PGMmYGMaRaFsO5VhiyKpSuRzHrabdgQnCrizMWKMPduoMjWAOI0HKqQdVhUTpDf+aO050rsJcDupWVAgNE7JiPFodZY3c2w1B0xCkWeC8Xj87A6KpktkN+VxHN62Nvr+x6eTZiInDftfJhq7u4jWYxeMoG79wm/VwJhiK8fCWAHv9vimlUDdqvWRzW21VGUoyUgHjpqCNhfP4IzuhOoEh+57iLEEU8NLlY2UpQfRkCmPQWI5UiiEuNoJxvdfhM+cbaaA1wn7o="

install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - export ARTIFACT_NAME="cas-oppija"
  - wget -q 'https://oph-public-files.s3-eu-west-1.amazonaws.com/adoptopenjdk/OpenJDK11U-jdk_x64_linux_hotspot_11.0.8_10.tar.gz'
  - tar xfz OpenJDK11U-jdk_x64_linux_hotspot_11.0.8_10.tar.gz
  - export JAVA_HOME=/home/travis/build/Opetushallitus/cas-oppija/jdk-11.0.8+10
  - export PATH=${JAVA_HOME}/bin:$PATH
  - java -version

script:
  - ./gradlew clean build -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}

  - mv build/libs/cas.war $DOCKER_BUILD_DIR/artifact/$ARTIFACT_NAME.jar
  - cp -vr oph-configuration $DOCKER_BUILD_DIR/config/

  - export BASE_IMAGE="baseimage-fatjar-openjdk11:master"
  - ./ci-tools/common/pull-image.sh
  - ./ci-tools/build/build-fatjar.sh $ARTIFACT_NAME

deploy:
  - provider: script
    script: ./ci-tools/build/upload-image.sh $ARTIFACT_NAME
    on:
      all_branches: true
