services:
  keycloak-postgres:
    container_name: cas-oppija-keycloak-postgres
    image: postgres:16.4
    ports:
      - "5082:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak

  keycloak:
    container_name: cas-oppija-keycloak
    image: quay.io/keycloak/keycloak:26.5.4
    command: ["start-dev", "--import-realm"]
    ports:
      - "127.0.0.1:8083:8080"
    expose:
      - "8083"
    environment:
      KC_HOSTNAME: "http://localhost:8083"
      KC_DB: postgres
      KC_DB_URL_HOST: host.docker.internal
      KC_DB_URL_PORT: 5082
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HTTP_ENABLED: true
      KC_OVERRIDE: true
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
      - ./keycloak/themes/dev-quicklogin:/opt/keycloak/themes/dev-quicklogin
    depends_on:
      - keycloak-postgres