server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;
    root    /usr/share/nginx/html;

    location / {
        try_files $uri $uri/ $uri.html index.html;
    }

    # Redirect to cas-oppija login
    location /secure {
        return 302 http://localhost:8081/cas-oppija/login?service=http%3A%2F%2Flocalhost%3A8080%2F;
    }

    location /logout {
        return 302 http://localhost:8081/cas-oppija/logout?service=http%3A%2F%2Flocalhost%3A8080%2F;
    }

    # Provide a mock endpoint that returns a mock oid, so that cas-oppija authentication passes
    # TODO: remove this and move to some place that is similar to implementations elsewhere
    location ~ ^/mock-oppijanumerorekisteri-service* {
        return 200 '1.2.3.4';
    }
}