name: CAS-virkailija deploy
on:
  workflow_dispatch:
    inputs:
      application:
        description: 'Name of the application (example: cas)'
        required: false
        type: string
        default: cas
      image-tag:
        description: 'Image tag (example: ga-956).'
        required: true
        type: string
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - hahtuva
          - untuva
          - pallero
          - sade
  
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: Opetushallitus/.github/.github/workflows/deploy-from-ecr-to-ecs.yml@main
    with:
      application: ${{ inputs.application }}
      environment: ${{ inputs.environment }}
      image-tag: ${{ inputs.image-tag }}
    secrets: inherit

