logging.config: file:/root/oph-configuration/cas-log4j.xml

cas.server.tomcat.http-proxy.enabled: true
cas.server.tomcat.http-proxy.secure: true
cas.server.tomcat.http-proxy.scheme: https
cas.server.tomcat.http-proxy.protocol: HTTP/1.1
cas.tgc.secure: true
cas.warning-cookie.secure: true
cas.tgc.pin-to-session: true
cas.tgc.crypto.encryption.key: ${cas_tgc_encryption_key}
cas.tgc.crypto.signing.key: ${cas_tgc_signing_key}
cas.webflow.crypto.encryption.key: ${cas_webflow_encryption_key}
cas.webflow.crypto.signing.key: ${cas_webflow_signing_key}

cas.view.default-redirect-url: https://virkailija.opintopolku.fi/virkailijan-tyopoyta

cas.authn.mfa.triggers.rest.url: https://virkailija.opintopolku.fi/kayttooikeus-service/mfa/trigger
cas.authn.mfa.triggers.rest.headers.Caller-Id: '1.2.246.562.10.00000000001.cas'
cas.authn.mfa.triggers.rest.headers.CSRF: '1.2.246.562.10.00000000001.cas'
cas.authn.mfa.triggers.rest.method: POST
cas.authn.mfa.triggers.rest.basic-auth-username: ${cas_mfa_username}
cas.authn.mfa.triggers.rest.basic-auth-password: ${cas_mfa_password}
cas.authn.mfa.gauth.cleaner.schedule.enabled: false
cas.authn.mfa.gauth.core.issuer: Opetushallitus
cas.authn.mfa.gauth.core.label: Opintopolku
cas.authn.mfa.gauth.crypto.encryption.key: ${cas_gauth_encryption_key}
cas.authn.mfa.gauth.crypto.signing.key: ${cas_gauth_signing_key}
cas.authn.mfa.gauth.rest.token-url: https://virkailija.opintopolku.fi/kayttooikeus-service/mfa/token
cas.authn.mfa.gauth.rest.url: https://virkailija.opintopolku.fi/kayttooikeus-service/mfa/token
cas.authn.mfa.gauth.rest.headers.Caller-Id: '1.2.246.562.10.00000000001.cas'
cas.authn.mfa.gauth.rest.headers.CSRF: '1.2.246.562.10.00000000001.cas'
cas.authn.mfa.gauth.rest.basic-auth-username: ${cas_mfa_username}
cas.authn.mfa.gauth.rest.basic-auth-password: ${cas_mfa_password}

cas.custom.properties.hakaUrl: https://virkailija.opintopolku.fi/service-provider-app/saml/login/alias/hakasp
cas.custom.properties.mpassidUrl: https://virkailija.opintopolku.fi/service-provider-app/saml/login/alias/mpassidsp?idp=https://mpass-proxy.csc.fi/idp/shibboleth
cas.custom.properties.suomifiUrl: https://opintopolku.fi/cas-oppija/login
cas.custom.properties.suomifiUrlTarget: https://virkailija.opintopolku.fi/kayttooikeus-service/cas/tunnistus?locale=
cas.custom.properties.loginTietosuojaselosteUrl: https://opintopolku.fi/konfo/fi/sivu/tietosuojaselosteet-ja-evasteet

cas.service-registry.json.location: file:///root/oph-configuration/cas

spring.datasource.url: jdbc:postgresql://${cas_postgres_host}:5432/cas
spring.datasource.driver-class-name: org.postgresql.Driver
spring.datasource.username: ${cas_postgres_username}
spring.datasource.password: ${cas_postgres_password}
cas.ticket.registry.core.enable-locking: false
cas.ticket.registry.jpa.enabled: true
cas.ticket.registry.jpa.driver-class: ${spring.datasource.driver-class-name}
cas.ticket.registry.jpa.password: ${spring.datasource.password}
cas.ticket.registry.jpa.url: ${spring.datasource.url}
cas.ticket.registry.jpa.user: ${spring.datasource.username}

management.endpoint.auditevents.enabled: false
management.endpoint.springWebflow.enabled: false

host.cas: virkailija.opintopolku.fi
host.virkailija: virkailija.opintopolku.fi
host.alb: virkailija.opintopolku.fi
serviceprovider.app.username.to.usermanagement: ${serviceprovider_app_username_to_usermanagement}
serviceprovider.app.password.to.usermanagement: ${serviceprovider_app_password_to_usermanagement}

# To all users
require-strong-identification: true
# To specified users even if cas.require-strong-identification is false
require-strong-identification.usernamelist: ""
# To all users
email-verification-enabled: true
# To specified users even if cas.email-verification-enabled is false
email-verification-enabled.usernamelist: ""
