SELECT insertkayttooikeus('KOSKI', 'AIKUISTENPERUSOPETUS__AIKUISTENPERUSOPETUKSENOPPIMAARANALKUVAIHE', 'Aikuisten perusopetus: Aikuisten perusopetuksen oppimäärän alkuvaihe');
SELECT insertkayttooikeus('KOSKI', 'AIKUISTENPERUSOPETUS__PERUSOPETUKSENOPPIAINEENOPPIMAARA', 'Aikuisten perusopetus: Perusopetuksen oppiaineen oppimäärä');
SELECT insertkayttooikeus('KOSKI', 'AIKUISTENPERUSOPETUS__AIKUISTENPERUSOPETUKSENOPPIMAARA', 'Aikuisten perusopetus: Aikuisten perusopetuksen oppimäärä');
SELECT insertkayttooikeus('KOSKI', 'AMMATILLINENKOULUTUS__AMMATILLINENTUTKINTOOSITTAINEN', 'Ammatillinen koulutus: Ammatillisen tutkinnon osa/osia');
SELECT insertkayttooikeus('KOSKI', 'AMMATILLINENKOULUTUS__AMMATILLINENTUTKINTO', 'Ammatillinen koulutus: Ammatillinen tutkinto');
SELECT insertkayttooikeus('KOSKI', 'AMMATILLINENKOULUTUS__MUUAMMATILLINENKOULUTUS', 'Ammatillinen koulutus: Muun ammatillisen koulutuksen suoritus');
SELECT insertkayttooikeus('KOSKI', 'AMMATILLINENKOULUTUS__NAYTTOTUTKINTOONVALMISTAVAKOULUTUS', 'Ammatillinen koulutus: Näyttötutkintoon valmistava koulutus');
SELECT insertkayttooikeus('KOSKI', 'AMMATILLINENKOULUTUS__TELMA', 'Ammatillinen koulutus: Työhön ja itsenäiseen elämään valmentava koulutus (TELMA)');
SELECT insertkayttooikeus('KOSKI', 'AMMATILLINENKOULUTUS__TUTKINNONOSAAPIENEMMISTÄKOKONAISUUKSISTAKOOSTUVASUORITUS', 'Ammatillinen koulutus: Tutkinnon osaa pienemmistä kokonaisuuksista koostuva suoritus');
SELECT insertkayttooikeus('KOSKI', 'AMMATILLINENKOULUTUS__VALMA', 'Ammatillinen koulutus: Ammatilliseen peruskoulutukseen valmentava koulutus (VALMA)');
SELECT insertkayttooikeus('KOSKI', 'DIATUTKINTO__DIATUTKINTOVAIHE', 'DIA-tutkinto: DIA-tutkintovaihe');
SELECT insertkayttooikeus('KOSKI', 'DIATUTKINTO__DIAVALMISTAVAVAIHE', 'DIA-tutkinto: Valmistava DIA-vaihe');
SELECT insertkayttooikeus('KOSKI', 'EUROPEANSCHOOLOFHELSINKI__EUROPEANSCHOOLOFHELSINKIVUOSILUOKKANURSERY', 'European School of Helsinki: European School of Helsinki nursery cycle year class');
SELECT insertkayttooikeus('KOSKI', 'EUROPEANSCHOOLOFHELSINKI__EUROPEANSCHOOLOFHELSINKIVUOSILUOKKAPRIMARY', 'European School of Helsinki: European School of Helsinki primary cycle year class');
SELECT insertkayttooikeus('KOSKI', 'EUROPEANSCHOOLOFHELSINKI__EUROPEANSCHOOLOFHELSINKIVUOSILUOKKASECONDARYLOWER', 'European School of Helsinki: European School of Helsinki secondary cycle lower year class');
SELECT insertkayttooikeus('KOSKI', 'EUROPEANSCHOOLOFHELSINKI__EUROPEANSCHOOLOFHELSINKIVUOSILUOKKASECONDARYUPPER', 'European School of Helsinki: European School of Helsinki secondary cycle upper year class');
SELECT insertkayttooikeus('KOSKI', 'IBTUTKINTO__IBTUTKINTO', 'IB-tutkinto: IB-tutkinto');
SELECT insertkayttooikeus('KOSKI', 'IBTUTKINTO__PREIBOPPIMAARA', 'IB-tutkinto: Pre-IB');
SELECT insertkayttooikeus('KOSKI', 'IBTUTKINTO__PREIBOPPIMAARA', 'IB-tutkinto: Pre-IB');
SELECT insertkayttooikeus('KOSKI', 'INTERNATIONALSCHOOL__INTERNATIONALSCHOOLDIPLOMAVUOSILUOKKA', 'International school: International school diploma vuosiluokka');
SELECT insertkayttooikeus('KOSKI', 'INTERNATIONALSCHOOL__INTERNATIONALSCHOOLMYPVUOSILUOKKA', 'International school: International school MYP vuosiluokka');
SELECT insertkayttooikeus('KOSKI', 'INTERNATIONALSCHOOL__INTERNATIONALSCHOOLPYPVUOSILUOKKA', 'International school: International school PYP vuosiluokka');
SELECT insertkayttooikeus('KOSKI', 'KIELITUTKINTO__VALTIONHALLINNONKIELITUTKINTO', 'Kielitutkinto: Valtionhallinnon kielitutkinto');
SELECT insertkayttooikeus('KOSKI', 'KIELITUTKINTO__YLEINENKIELITUTKINTO', 'Kielitutkinto: Yleinen kielitutkinto');
SELECT insertkayttooikeus('KOSKI', 'LUKIOKOULUTUS__LUKIONOPPIAINEENOPPIMAARA', 'Lukiokoulutus: Lukion oppiaineen oppimäärä');
SELECT insertkayttooikeus('KOSKI', 'LUKIOKOULUTUS__LUKIONAINEOPINNOT', 'Lukiokoulutus: Lukion aineopinnot');
SELECT insertkayttooikeus('KOSKI', 'LUKIOKOULUTUS__LUKIONOPPIMAARA', 'Lukiokoulutus: Lukion oppimäärä');
SELECT insertkayttooikeus('KOSKI', 'LUKIOKOULUTUS__LUKIONOPPIMAARA', 'Lukiokoulutus: Lukion oppimäärä');
SELECT insertkayttooikeus('KOSKI', 'PERUSOPETUS__NUORTENPERUSOPETUKSENOPPIAINEENOPPIMAARA', 'Perusopetus: Nuorten perusopetuksen oppiaineen oppimäärä');
SELECT insertkayttooikeus('KOSKI', 'PERUSOPETUS__PERUSOPETUKSENOPPIMAARA', 'Perusopetus: Perusopetuksen oppimäärä');
SELECT insertkayttooikeus('KOSKI', 'PERUSOPETUS__PERUSOPETUKSENVUOSILUOKKA', 'Perusopetus: Perusopetuksen vuosiluokka');
SELECT insertkayttooikeus('KOSKI', 'TAITEENPERUSOPETUS__TAITEENPERUSOPETUKSENLAAJANOPPIMAARANPERUSOPINNOT', 'Taiteen perusopetus: Taiteen perusopetuksen laajan oppimäärän perusopintojen suoritus');
SELECT insertkayttooikeus('KOSKI', 'TAITEENPERUSOPETUS__TAITEENPERUSOPETUKSENLAAJANOPPIMAARANSYVENTAVATOPINNOT', 'Taiteen perusopetus: Taiteen perusopetuksen laajan oppimäärän syventävien opintojen suoritus');
SELECT insertkayttooikeus('KOSKI', 'TAITEENPERUSOPETUS__TAITEENPERUSOPETUKSENYLEISENOPPIMAARANTEEMAOPINNOT', 'Taiteen perusopetus: Taiteen perusopetuksen yleisen oppimäärän teemaopintojen suoritus');
SELECT insertkayttooikeus('KOSKI', 'TAITEENPERUSOPETUS__TAITEENPERUSOPETUKSENYLEISENOPPIMAARANYHTEISETOPINNOT', 'Taiteen perusopetus: Taiteen perusopetuksen yleisen oppimäärän yhteisten opintojen suoritus');
SELECT insertkayttooikeus('KOSKI', 'VAPAANSIVISTYSTYONKOULUTUS__VSTMAAHANMUUTTAJIENKOTOUTUMISKOULUTUS', 'Vapaan sivistystyön koulutus: Vapaan sivistystyön maahanmuuttajien kotoutumiskoulutus');
SELECT insertkayttooikeus('KOSKI', 'VAPAANSIVISTYSTYONKOULUTUS__VSTMAAHANMUUTTAJIENKOTOUTUMISKOULUTUS', 'Vapaan sivistystyön koulutus: Vapaan sivistystyön maahanmuuttajien kotoutumiskoulutus');
SELECT insertkayttooikeus('KOSKI', 'VAPAANSIVISTYSTYONKOULUTUS__VSTOPPIVELVOLLISILLESUUNNATTUKOULUTUS', 'Vapaan sivistystyön koulutus: Oppivelvollisille suunnattu vapaan sivistystyön koulutus');
SELECT insertkayttooikeus('KOSKI', 'VAPAANSIVISTYSTYONKOULUTUS__VSTJOTPAKOULUTUS', 'Vapaan sivistystyön koulutus: Jatkuvaan oppimiseen suunnattu vapaan sivistystyön koulutus');
SELECT insertkayttooikeus('KOSKI', 'VAPAANSIVISTYSTYONKOULUTUS__VSTLUKUTAITOKOULUTUS', 'Vapaan sivistystyön koulutus: Vapaan sivistystyön lukutaitokoulutus');
SELECT insertkayttooikeus('KOSKI', 'VAPAANSIVISTYSTYONKOULUTUS__VSTOSAAMISMERKKI', 'Vapaan sivistystyön koulutus: Vapaan sivistystyön osaamismerkki');
SELECT insertkayttooikeus('KOSKI', 'VAPAANSIVISTYSTYONKOULUTUS__VSTVAPAATAVOITTEINENKOULUTUS', 'Vapaan sivistystyön koulutus: Vapaan sivistystyön vapaatavoitteinen koulutus');