SELECT insertkayttooikeus('KOSKI', 'OMADATAOAUTH2_OPISKELUOIKEUDET_SUORITETUT_TUTKINNOT', 'OmaData OAuth2 scope OPISKELUOIKEUDET_SUORITETUT_TUTKINNOT');
SELECT insertkayttooikeus('KOSKI', 'OMADATAOAUTH2_OPISKELUOIKEUDET_AKTIIVISET_JA_PAATTYNEET_OPINNOT', 'OmaData OAuth2 scope OPISKELUOIKEUDET_AKTIIVISET_JA_PAATTYNEET_OPINNOT');
SELECT insertkayttooikeus('KOSKI', 'OMADATAOAUTH2_OPISKELUOIKEUDET_KAIKKI_TIEDOT', 'OmaData OAuth2 scope OPISKELUOIKEUDET_KAIKKI_TIEDOT');
SELECT insertkayttooikeus('KOSKI', 'OMADATAOAUTH2_HENKILOTIEDOT_NIMI', 'OmaData OAuth2 scope HENKILOTIEDOT_NIMI');
SELECT insertkayttooikeus('KOSKI', 'OMADATAOAUTH2_HENKILOTIEDOT_SYNTYMAAIKA', 'OmaData OAuth2 scope HENKILOTIEDOT_SYNTYMAAIKA');
SELECT insertkayttooikeus('KOSKI', 'OMADATAOAUTH2_HENKILOTIEDOT_HETU', 'OmaData OAuth2 scope HENKILOTIEDOT_HETU');
SELECT insertkayttooikeus('KOSKI', 'OMADATAOAUTH2_HENKILOTIEDOT_KAIKKI_TIEDOT', 'OmaData OAuth2 scope HENKILOTIEDOT_KAIKKI_TIEDOT');