kayttooikeus.baseurl: https://kayttooikeus.dev.yleiskayttoiset.opintopolku.fi
cas.server.name: https://virkailija.untuvaopintopolku.fi
cas.server.prefix: ${cas.server.name}/cas
cas.server.tomcat.http-proxy.enabled: true
cas.server.tomcat.http-proxy.secure: true
cas.server.tomcat.http-proxy.scheme: https
cas.server.tomcat.http-proxy.protocol: HTTP/1.1
cas.tgc.secure: true
cas.warning-cookie.secure: true
cas.tgc.pin-to-session: true
cas.tgc.crypto.encryption.key: ${cas_tgc_encryption_key}
cas.tgc.crypto.signing.key: ${cas_tgc_signing_key}
cas.webflow.crypto.encryption.key: ${cas_webflow_encryption_key}
cas.webflow.crypto.signing.key: ${cas_webflow_signing_key}

cas.view.default-redirect-url: https://virkailija.untuvaopintopolku.fi/virkailijan-tyopoyta

cas.authn.mfa.triggers.rest.url: https://virkailija.untuvaopintopolku.fi/kayttooikeus-service/mfa/trigger
cas.authn.mfa.triggers.rest.headers.Caller-Id: '1.2.246.562.10.00000000001.cas'
cas.authn.mfa.triggers.rest.headers.CSRF: '1.2.246.562.10.00000000001.cas'
cas.authn.mfa.triggers.rest.method: POST
cas.authn.mfa.triggers.rest.basic-auth-username: ${cas_mfa_username}
cas.authn.mfa.triggers.rest.basic-auth-password: ${cas_mfa_password}
cas.authn.mfa.gauth.cleaner.schedule.enabled: false
cas.authn.mfa.gauth.core.issuer: Opetushallitus
cas.authn.mfa.gauth.core.label: Opintopolku
cas.authn.mfa.gauth.crypto.encryption.key: ${cas_gauth_encryption_key}
cas.authn.mfa.gauth.crypto.signing.key: ${cas_gauth_signing_key}
cas.authn.mfa.gauth.rest.token-url: https://virkailija.untuvaopintopolku.fi/kayttooikeus-service/mfa/token
cas.authn.mfa.gauth.rest.url: https://virkailija.untuvaopintopolku.fi/kayttooikeus-service/mfa/token
cas.authn.mfa.gauth.rest.headers.Caller-Id: '1.2.246.562.10.00000000001.cas'
cas.authn.mfa.gauth.rest.headers.CSRF: '1.2.246.562.10.00000000001.cas'
cas.authn.mfa.gauth.rest.basic-auth-username: ${cas_mfa_username}
cas.authn.mfa.gauth.rest.basic-auth-password: ${cas_mfa_password}

cas.custom.properties.hakaUrl: https://virkailija.untuvaopintopolku.fi/service-provider-app/saml/login/alias/hakasp
cas.custom.properties.suomifiUrl: https://untuvaopintopolku.fi/cas-oppija/login
cas.custom.properties.suomifiUrlTarget: https://virkailija.untuvaopintopolku.fi/kayttooikeus-service/cas/tunnistus?locale=
cas.custom.properties.loginTietosuojaselosteUrl: https://opintopolku.fi/konfo/fi/sivu/tietosuojaselosteet-ja-evasteet

cas.service-registry.json.location: file:///app/services/dev

cas.authn.pac4j.core.session-replication.cookie.crypto.encryption.key: ${cas_pac4j_encryption_key}
cas.authn.pac4j.core.session-replication.cookie.crypto.signing.key: ${cas_pac4j_signing_key}
cas.authn.pac4j.oidc[0].generic.discovery-uri: https://mpass-proxy-test.csc.fi/.well-known/openid-configuration
cas.authn.pac4j.oidc[0].generic.id: ${cas_mpassid_oidc_id}
cas.authn.pac4j.oidc[0].generic.secret: ${cas_mpassid_oidc_secret}
cas.authn.pac4j.oidc[0].generic.client-name: mpassid
cas.authn.pac4j.oidc[0].generic.principal-id-attribute: urn:oid:1.3.6.1.4.1.16161.1.1.27
cas.authn.pac4j.saml[0].keystore-password: ${cas_haka_keystore_password}
cas.authn.pac4j.saml[0].private-key-password: ${cas_haka_keystore_password}
cas.authn.pac4j.saml[0].service-provider-entity-id: https://virkailija.untuvaopintopolku.fi/cas/login/haka
cas.authn.pac4j.saml[0].metadata.identity-provider-metadata-path: https://haka.funet.fi/metadata/haka-metadata-v9.xml
cas.authn.pac4j.saml[0].metadata.service-provider.file-system.location: /app/etc/hakasp.xml
cas.authn.pac4j.saml[0].keystore-path: /app/etc/hakakeystore.jks
cas.authn.pac4j.saml[0].destination-binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect
cas.authn.pac4j.saml[0].logout-response-binding-type: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect
cas.authn.pac4j.saml[0].client-name: haka
cas.authn.pac4j.saml[0].sign-authn-request: true
cas.authn.pac4j.saml[0].wants-assertions-signed: true
cas.authn.pac4j.saml[0].wants-responses-signed: true
cas.authn.pac4j.saml[0].sign-service-provider-logout-request: true
cas.authn.pac4j.saml[0].use-name-qualifier: false
cas.authn.pac4j.saml[0].maximum-authentication-lifetime: PT31536000S
cas.authn.pac4j.saml[0].accepted-skew: PT7200S
cas.authn.pac4j.saml[0].discovery-service-url: https://haka.funet.fi/DS

# postgres
spring.datasource.url: jdbc:postgresql://${cas_postgres_host}:${cas_postgres_port}/${cas_postgres_database}
spring.datasource.driver-class-name: org.postgresql.Driver
spring.datasource.username: ${cas_postgres_username}
spring.datasource.password: ${cas_postgres_password}
cas.ticket.registry.core.enable-locking: false
cas.ticket.registry.jpa.enabled: true
cas.ticket.registry.jpa.driver-class: ${spring.datasource.driver-class-name}
cas.ticket.registry.jpa.password: ${spring.datasource.password}
cas.ticket.registry.jpa.url: ${spring.datasource.url}
cas.ticket.registry.jpa.user: ${spring.datasource.username}

management.endpoint.auditevents.enabled: false
management.endpoint.springWebflow.enabled: false

host.cas: virkailija.untuvaopintopolku.fi
host.virkailija: virkailija.untuvaopintopolku.fi
host.alb: virkailija.untuvaopintopolku.fi
serviceprovider.app.username.to.usermanagement: ${serviceprovider_app_username_to_usermanagement}
serviceprovider.app.password.to.usermanagement: ${serviceprovider_app_password_to_usermanagement}
# To all users
require-strong-identification: false
# To specified users even if cas.require-strong-identification is false
require-strong-identification.usernamelist: ""
# To all users
email-verification-enabled: false
# To specified users even if cas.email-verification-enabled is false
email-verification-enabled.usernamelist: ""
