spring.datasource.url: jdbc:postgresql://host.docker.internal:5080/cas

management.endpoints.web.exposure.include: health,springWebflow,auditevents
management.endpoint.auditevents.access: READ_ONLY
management.endpoint.springWebflow.access: READ_ONLY

cas.server.name: http://localhost:8080
cas.server.prefix: ${cas.server.name}/cas
cas.ticket.registry.jpa.url: ${spring.datasource.url}
cas.tgc.secure: false
cas.warning-cookie.secure: false

cas.custom.properties.uusHakaEnabled: true
cas.custom.properties.uusSuomifiEnabled: true
cas.custom.properties.suomifiUrlTarget: http://host.docker.internal:8101/kayttooikeus-service/cas/tunnistus?locale=

cas.authn.mfa.triggers.rest.url: http://host.docker.internal:8101/kayttooikeus-service/mfa/trigger
cas.authn.mfa.gauth.rest.token-url: http://host.docker.internal:8101/kayttooikeus-service/mfa/token
cas.authn.mfa.gauth.rest.url: http://host.docker.internal:8101/kayttooikeus-service/mfa/token

cas.service-registry.json.location: file:///app/services/local

host.alb: host.docker.internal:8101
kayttooikeus.baseurl: http://host.docker.internal:8101

cas.authn.pac4j.oidc[0].generic.discovery-uri: https://mpass-proxy-test.csc.fi/.well-known/openid-configuration
cas.authn.pac4j.oidc[0].generic.id: dummy
cas.authn.pac4j.oidc[0].generic.secret: dummy
cas.authn.pac4j.oidc[0].generic.client-name: mpassid
cas.authn.pac4j.oidc[0].generic.principal-id-attribute: urn:oid:1.3.6.1.4.1.16161.1.1.27

cas.authn.pac4j.saml[0].client-name: haka
cas.authn.pac4j.saml[0].keystore-password: dummy
cas.authn.pac4j.saml[0].private-key-password: dummy
cas.authn.pac4j.saml[0].service-provider-entity-id: http://localhost:8080/cas/login/haka
cas.authn.pac4j.saml[0].metadata.service-provider.file-system.location: /app/etc/localhakasp.xml
cas.authn.pac4j.saml[0].keystore-path: /app/etc/localhakakeystore.jks
cas.authn.pac4j.saml[0].metadata.identity-provider-metadata-path: https://haka.funet.fi/metadata/haka_test_metadata_signed.xml
cas.authn.pac4j.saml[0].sign-authn-request: true
cas.authn.pac4j.saml[0].wants-assertions-signed: true
cas.authn.pac4j.saml[0].wants-responses-signed: true
cas.authn.pac4j.saml[0].sign-service-provider-logout-request: true
cas.authn.pac4j.saml[0].use-name-qualifier: false
cas.authn.pac4j.saml[0].maximum-authentication-lifetime: PT31536000S
cas.authn.pac4j.saml[0].accepted-skew: PT7200S

cas.authn.pac4j.saml[1].client-name: suomifi
cas.authn.pac4j.saml[1].keystore-password: dummy
cas.authn.pac4j.saml[1].private-key-password: dummy
cas.authn.pac4j.saml[1].keystore-path: /app/etc/localsuomifikeystore.jks
cas.authn.pac4j.saml[1].service-provider-entity-id: http://localhost:8080/cas/login/suomifi
cas.authn.pac4j.saml[1].metadata.service-provider.file-system.location: /app/etc/localsuomifi.xml
cas.authn.pac4j.saml[1].metadata.identity-provider-metadata-path: https://static.apro.tunnistus.fi/static/metadata/idp-metadata.xml
cas.authn.pac4j.saml[1].destination-binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
cas.authn.pac4j.saml[1].logout-response-binding-type: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
cas.authn.pac4j.saml[1].sign-authn-request: true
cas.authn.pac4j.saml[1].wants-assertions-signed: true
cas.authn.pac4j.saml[1].wants-responses-signed: true
cas.authn.pac4j.saml[1].sign-service-provider-logout-request: true
cas.authn.pac4j.saml[1].use-name-qualifier: false
cas.authn.pac4j.saml[1].principal-id-attribute: nationalIdentificationNumber
cas.authn.pac4j.saml[1].requested-attributes[0].name: urn:oid:1.2.246.21
cas.authn.pac4j.saml[1].requested-attributes[0].friendly-name: nationalIdentificationNumber
cas.authn.pac4j.saml[1].requested-attributes[0].name-format: urn:oasis:names:tc:SAML:2.0:attrname-format:uri
cas.authn.pac4j.saml[1].requested-attributes[0].required: true